logLevel: info

api: yes
apiAddress: :9997

rtsp: yes
rtspAddress: :8554

hls: yes
hlsAddress: :8888
hlsAlwaysRemux: no

webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189

paths:
  original:
    source: publisher
  rendered:
    source: publisher
